/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package newshog.thrift.server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AnalysisOptions implements org.apache.thrift.TEnum {
  All(0),
  Summarization(1),
  TextRank(2),
  LexChain(3),
  Wiki(4),
  Twitter(8),
  Sentiment(16);

  private final int value;

  private AnalysisOptions(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AnalysisOptions findByValue(int value) { 
    switch (value) {
      case 0:
        return All;
      case 1:
        return Summarization;
      case 2:
        return TextRank;
      case 3:
        return LexChain;
      case 4:
        return Wiki;
      case 8:
        return Twitter;
      case 16:
        return Sentiment;
      default:
        return null;
    }
  }
}
